---
title: "Reschedule opportunity"
author: "Rojiar"
date: "August 29, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Progressive Buildings

```{r,echo=FALSE}

setwd("~/17-edifes/data/Progressive")


library(data.table)
library(ggplot2)

data_preprocess=function(dat){
  p=which(as.integer(dat$num_time)==0)
  if(p[1]>0){
    l=p[1]-1
  dat = dat[-c(1:l),]
  }
  last<-which(as.integer(dat$num_time,2)==23)
  last<-max(last)
  if(last<length(dat$num_time)){
    full=length(dat$num_time)
    dat=dat[-c({last+1}:full),]
  }
#  dat$norm = (dat$elec_cons - min(dat$elec_cons))/(max(dat$elec_cons)-min(dat$elec_cons))
  return(dat)
}

temp<-list.files(pattern = "f-*")

for(z in 1:length(temp)){
 # for(z in 1:1){
A<-fread(temp[z])
print(temp[z])
A<-as.data.frame(A)
A$timestamp<-as.POSIXct(A$timestamp)
A$time<-as.Date(as.character(A$timestamp))

A<-data_preprocess(A)
A$elec_cons<-A$forecast

#A$elec_cons<-A$cleaned_energy
A_biz<-A[which(A$biz_day==1),]
A_nonbiz<-A[which(A$biz_day==0),]

Base_biz_data<-A_biz[A_biz$num_time<7 | A_biz$num_time>19,]
pick_biz_data<-A_biz[A_biz$num_time>=7 & A_biz$num_time<=19,]


#Base_biz_data<-A_biz[A_biz$num_time<8.5 | A_biz$num_time>15.5,]
#pick_biz_data<-A_biz[A_biz$num_time>=8.5 & A_biz$num_time<=15.5,]


Base_biz_meanEnergy<-aggregate(Base_biz_data$elec_cons,by=list(Base_biz_data$time),mean)
colnames(Base_biz_meanEnergy) <- c("Date","BaseEnergyMean")

pick_biz_meanEnergy<-aggregate(pick_biz_data$elec_cons,by=list(pick_biz_data$time),mean)
colnames(pick_biz_meanEnergy) <- c("Date","PickEnergyMean")

Base_nonbiz_data<-A_nonbiz[A_nonbiz$num_time<7 | A_nonbiz$num_time>19,]
pick_nonbiz_data<-A_nonbiz[A_nonbiz$num_time>=7 & A_nonbiz$num_time<=19,]

#Base_nonbiz_data<-A_nonbiz[A_nonbiz$num_time<8.5 | A_nonbiz$num_time>15.5,]
#pick_nonbiz_data<-A_nonbiz[A_nonbiz$num_time>=8.5 & A_nonbiz$num_time<=15.5,]




Base_nonbiz_meanEnergy<-aggregate(Base_nonbiz_data$elec_cons,by=list(Base_nonbiz_data$time),mean)
colnames(Base_nonbiz_meanEnergy) <- c("Date","BaseEnergyMean")

pick_nonbiz_meanEnergy<-aggregate(pick_nonbiz_data$elec_cons,by=list(pick_nonbiz_data$time),mean)
colnames(pick_nonbiz_meanEnergy) <- c("Date","PickEnergyMean")

biz_meanEnergy<-cbind(Base_biz_meanEnergy,pick_biz_meanEnergy)
nonbiz_meanEnergy<-cbind(Base_nonbiz_meanEnergy,pick_nonbiz_meanEnergy)
biz_meanEnergy<-biz_meanEnergy[,-3]
nonbiz_meanEnergy<-nonbiz_meanEnergy[,-3]

Tests<-matrix(rep(0,4),4,1)
Tests<-as.data.frame(Tests)
row.names(Tests)<-c("Statistic","p_value","Estimate1","Estimate2")

Biz_PickBase<-t.test(biz_meanEnergy$PickEnergyMean,biz_meanEnergy$BaseEnergyMean,paired=TRUE)
Tests[,1]<-c(Biz_PickBase$statistic,Biz_PickBase$p.value,Biz_PickBase$estimate,"NA")
names(Tests)<-c("Biz_PickBase")
if(Biz_PickBase$p.value>0.01){cat("\n Mean energy consumption of Night and Day for bussines days are the same.",sep="\n")
} else {
  cat(" Mean energy consumption of Night and Day for bussines days are different,  \n Builing is scheduled on nights.",sep="\n")
}

if (Biz_PickBase$estimate>0){cat("Mean energy consumption of Night < Day for bussines days.",sep="\n")
} else {
  cat(" Mean energy consumption of Night > Day for bussines days.",sep="\n")
}

NonBiz_PickBase<-t.test(nonbiz_meanEnergy$PickEnergyMean,nonbiz_meanEnergy$BaseEnergyMean,paired=TRUE)
Tests$NonBiz_PickBase<-c(NonBiz_PickBase$statistic,NonBiz_PickBase$p.value,NonBiz_PickBase$estimate,"NA")
if(NonBiz_PickBase$p.value<0.1){cat("\n  Mean energy consumption of Night and Day for nonbussines days are different",sep="\n")
} else {
  cat("  \n Mean energy consumption of Night and Day for nonbussines days are the same.",sep="\n")
}


if (NonBiz_PickBase$estimate>0){cat("Mean energy consumption of Night < Day for non_bussines days.",sep="\n")
} else {
  cat(" Mean energy consumption of Night > Day for non_bussines days.",sep="\n")
}
  

Base_BizNonbiz<-t.test(biz_meanEnergy$BaseEnergyMean,nonbiz_meanEnergy$BaseEnergyMean,var.equal = TRUE)
Tests$Base_BizNonbiz<-c(Base_BizNonbiz$statistic,Base_BizNonbiz$p.value,Base_BizNonbiz$estimate)
if(Base_BizNonbiz$p.value<0.1){cat("  \n Night schedule for bussines and nonbussines days are different.",sep="\n")
}else{
  cat("  \n Night schedule for bussines and nonbussines days are the same, \n Building is scheduled at night-time.",sep="\n")
}


if (Base_BizNonbiz$estimate[1]>Base_BizNonbiz$estimate[2]){cat("Mean energy consumption of Nights for bussines > nonbussines.",sep="\n")
} else {
  cat(" Mean energy consumption of Nights for bussines < nonbussines.",sep="\n")
}
  

Pick_BizNonbiz<-t.test(biz_meanEnergy$PickEnergyMean,nonbiz_meanEnergy$PickEnergyMean,var.equal = TRUE)
Tests$Pick_BizNonbiz<-c(Pick_BizNonbiz$statistic,Pick_BizNonbiz$p.value,Pick_BizNonbiz$estimate)
if(Pick_BizNonbiz$p.value>0.01){cat("  \n Day schedule for bussines and nonbussines days are the same.",sep="\n")
}else{
  cat("  \n Day schedule for bussines and nonbussines days are different,  \n Building is scheduled at day-time.",sep="\n")
}


if (Pick_BizNonbiz$estimate[1]>Pick_BizNonbiz$estimate[2]){cat("Mean energy consumption of days for bussines > nonbussines.",sep="\n")
} else {
  cat(" Mean energy consumption of days for bussines < nonbussines.",sep="\n")
}
  

plot10<-ggplot(A[1:3000,],aes(x = timestamp, y = elec_cons)) +
  geom_line(size = 1) +
  ylab("Energy") +
  xlab("Date") 

print(list(Tests,plot10))
}




```

#KSU Buildings

```{r,echo=FALSE}

setwd("~/17-edifes/data/KSU/KWH")


library(data.table)
library(ggplot2)

data_preprocess=function(dat){
  p=which(as.integer(dat$num_time)==0)
  if(p[1]>0){
    l=p[1]-1
  dat = dat[-c(1:l),]
  }
  last<-which(as.integer(dat$num_time,2)==23)
  last<-max(last)
  if(last<length(dat$num_time)){
    full=length(dat$num_time)
    dat=dat[-c({last+1}:full),]
  }
#  dat$norm = (dat$elec_cons - min(dat$elec_cons))/(max(dat$elec_cons)-min(dat$elec_cons))
  return(dat)
}

temp<-list.files(pattern = "f-*")

#for(z in 1:length(temp)){
  for(z in 1:14){
A<-fread(temp[z])
print(temp[z])
A<-as.data.frame(A)
A$timestamp<-as.POSIXct(A$timestamp)
A$time<-as.Date(as.character(A$timestamp))

A<-data_preprocess(A)
A$elec_cons<-A$forecast

#A$elec_cons<-A$cleaned_energy
A_biz<-A[which(A$biz_day==1),]
A_nonbiz<-A[which(A$biz_day==0),]

Base_biz_data<-A_biz[A_biz$num_time<7 | A_biz$num_time>19,]
pick_biz_data<-A_biz[A_biz$num_time>=7 & A_biz$num_time<=19,]


#Base_biz_data<-A_biz[A_biz$num_time<8.5 | A_biz$num_time>15.5,]
#pick_biz_data<-A_biz[A_biz$num_time>=8.5 & A_biz$num_time<=15.5,]


Base_biz_meanEnergy<-aggregate(Base_biz_data$elec_cons,by=list(Base_biz_data$time),mean)
colnames(Base_biz_meanEnergy) <- c("Date","BaseEnergyMean")

pick_biz_meanEnergy<-aggregate(pick_biz_data$elec_cons,by=list(pick_biz_data$time),mean)
colnames(pick_biz_meanEnergy) <- c("Date","PickEnergyMean")

Base_nonbiz_data<-A_nonbiz[A_nonbiz$num_time<7 | A_nonbiz$num_time>19,]
pick_nonbiz_data<-A_nonbiz[A_nonbiz$num_time>=7 & A_nonbiz$num_time<=19,]

#Base_nonbiz_data<-A_nonbiz[A_nonbiz$num_time<8.5 | A_nonbiz$num_time>15.5,]
#pick_nonbiz_data<-A_nonbiz[A_nonbiz$num_time>=8.5 & A_nonbiz$num_time<=15.5,]




Base_nonbiz_meanEnergy<-aggregate(Base_nonbiz_data$elec_cons,by=list(Base_nonbiz_data$time),mean)
colnames(Base_nonbiz_meanEnergy) <- c("Date","BaseEnergyMean")

pick_nonbiz_meanEnergy<-aggregate(pick_nonbiz_data$elec_cons,by=list(pick_nonbiz_data$time),mean)
colnames(pick_nonbiz_meanEnergy) <- c("Date","PickEnergyMean")

biz_meanEnergy<-cbind(Base_biz_meanEnergy,pick_biz_meanEnergy)
nonbiz_meanEnergy<-cbind(Base_nonbiz_meanEnergy,pick_nonbiz_meanEnergy)
biz_meanEnergy<-biz_meanEnergy[,-3]
nonbiz_meanEnergy<-nonbiz_meanEnergy[,-3]

Tests<-matrix(rep(0,4),4,1)
Tests<-as.data.frame(Tests)
row.names(Tests)<-c("Statistic","p_value","Estimate1","Estimate2")

Biz_PickBase<-t.test(biz_meanEnergy$PickEnergyMean,biz_meanEnergy$BaseEnergyMean,paired=TRUE)
Tests[,1]<-c(Biz_PickBase$statistic,Biz_PickBase$p.value,Biz_PickBase$estimate,"NA")
names(Tests)<-c("Biz_PickBase")
if(Biz_PickBase$p.value>0.01){cat("\n Mean energy consumption of Night and Day for bussines days are the same.",sep="\n")
} else {
  cat(" Mean energy consumption of Night and Day for bussines days are different,  \n Builing is scheduled on nights.",sep="\n")
}

if (Biz_PickBase$estimate>0){cat("Mean energy consumption of Night < Day for bussines days.",sep="\n")
} else {
  cat(" Mean energy consumption of Night > Day for bussines days.",sep="\n")
}

NonBiz_PickBase<-t.test(nonbiz_meanEnergy$PickEnergyMean,nonbiz_meanEnergy$BaseEnergyMean,paired=TRUE)
Tests$NonBiz_PickBase<-c(NonBiz_PickBase$statistic,NonBiz_PickBase$p.value,NonBiz_PickBase$estimate,"NA")
if(NonBiz_PickBase$p.value<0.1){cat("\n  Mean energy consumption of Night and Day for nonbussines days are different",sep="\n")
} else {
  cat("  \n Mean energy consumption of Night and Day for nonbussines days are the same.",sep="\n")
}


if (NonBiz_PickBase$estimate>0){cat("Mean energy consumption of Night < Day for non_bussines days.",sep="\n")
} else {
  cat(" Mean energy consumption of Night > Day for non_bussines days.",sep="\n")
}
  

Base_BizNonbiz<-t.test(biz_meanEnergy$BaseEnergyMean,nonbiz_meanEnergy$BaseEnergyMean,var.equal = TRUE)
Tests$Base_BizNonbiz<-c(Base_BizNonbiz$statistic,Base_BizNonbiz$p.value,Base_BizNonbiz$estimate)
if(Base_BizNonbiz$p.value<0.1){cat("  \n Night schedule for bussines and nonbussines days are different.",sep="\n")
}else{
  cat("  \n Night schedule for bussines and nonbussines days are the same, \n Building is scheduled at night-time.",sep="\n")
}


if (Base_BizNonbiz$estimate[1]>Base_BizNonbiz$estimate[2]){cat("Mean energy consumption of Nights for bussines > nonbussines.",sep="\n")
} else {
  cat(" Mean energy consumption of Nights for bussines < nonbussines.",sep="\n")
}
  

Pick_BizNonbiz<-t.test(biz_meanEnergy$PickEnergyMean,nonbiz_meanEnergy$PickEnergyMean,var.equal = TRUE)
Tests$Pick_BizNonbiz<-c(Pick_BizNonbiz$statistic,Pick_BizNonbiz$p.value,Pick_BizNonbiz$estimate)
if(Pick_BizNonbiz$p.value>0.01){cat("  \n Day schedule for bussines and nonbussines days are the same.",sep="\n")
}else{
  cat("  \n Day schedule for bussines and nonbussines days are different,  \n Building is scheduled at day-time.",sep="\n")
}


if (Pick_BizNonbiz$estimate[1]>Pick_BizNonbiz$estimate[2]){cat("Mean energy consumption of days for bussines > nonbussines.",sep="\n")
} else {
  cat(" Mean energy consumption of days for bussines < nonbussines.",sep="\n")
}
  

plot10<-ggplot(A[1:3000,],aes(x = timestamp, y = elec_cons)) +
  geom_line(size = 1) +
  ylab("Energy") +
  xlab("Date") 

print(list(Tests,plot10))
}




```


