---
title: "EDA Code Book"
author: "Will Koehrsen"
date: "December 7, 2017"
output: pdf_document
---

<!--
  # Script Name: codebook.Rmd
  # Purpose: Code Book for DSCI 451 Semester Project
  # Authors: William Koehrsen
  # License: Creative Commons Attribution-ShareAlike 4.0 International License.
  ##########
# Latest Changelog Entries:
# v0.00.01 - 12/07/17 - codebook.Rmd - William Koehrsen began this rmd
# v0.00.02 - 12/07/17 - codebook.Rmd - William Koehrsen finished data book

##########

# Rmd code goes below the comment marker!
-->
# Purpose 

This file documents all of the code used in the Progressive Building Energy EDA.

# R Code

All R code was written in Rmd (R markdown) files. This facilitated documentation 
of code and allowed for workflow of: ask question - write code to try to discover 
answer - report results and conclusions.

* eda_report_one.Rmd: Examined available data, posed guiding questions, 
preliminary exploratory graphics
* eda_report_two.Rmd: Comprehensive eda, examined correlations between 
explanatory and response variables, visualized and quantified
patterns and relationships, investigated modeling approaches
* eda_report_three.Rmd: Compared models for predicting energy use,
selected best performing model for optimizing, interpreted results of model,
challenged modeled, perform experimental modeling, and formed conclusions from
model output

# Python Code

Python, and in particular, the Scikit-learn library was used to implement the
machine learning algorithms. Python implementations are much faster than those in R,
and dataframes can be passed quickly back and forth between the languages
using the feather file format. 

Development work was completed in Jupyter Notebooks and then code was transferred
to Python scripts for use. The Jupyter Notebooks were not documented as thoroughly
as the R markdown files because of time constraints. Initially, feature 
preparation was completed in Python, but was then switched to R as documented in
Report Three. This process allowed the benefits of both languages to be used,
the speed of Python and the data manipulation capabilities of the R language. This 
workflow was not optimal, and I have since found the 'ranger' random 
forest package in R with much greater speed than randomForest. The ranger package 
will be used for implementing the random forest model in subsequent work.

* eda_report_two.ipynb: Development work to test the models, exploratory modeling
techniques, testing various feature transformations, assessing accuracy of 
various models
* modeling.ipynb: Actual machine learning model comparisons; training, testing, 
evaluating models; optimizing hyperparameters of selected Random Forest model,
saving results for interpretation, challenging model to predict energy use.

* model_utilities.py: Feature preparation functions, model implementation functions,
training and testing, challenging model
* rf_model.py: Command line arguments for interacting with functions in 
model_utilities.py, used to specify building for training and testing

The final Python code used in the project was also documented in report three 
to inform the readers. All the Python code in the preceding scripts and 
Notebooks was not necessarily used in the final reports. 