---
title: "EDA Data Book"
author: "Will Koehrsen"
date: "December 7, 2017"
output: pdf_document
---

<!--
  # Script Name: databook.Rmd
  # Purpose: Data Book for DSCI 451 Semester Project
  # Authors: William Koehrsen
  # License: Creative Commons Attribution-ShareAlike 4.0 International License.
  ##########
# Latest Changelog Entries:
# v0.00.01 - 12/07/17 - databook.Rmd - William Koehrsen began this rmd
# v0.00.02 - 12/07/17 - databook.Rmd - William Koehrsen finished data book

##########

# Rmd code goes below the comment marker!
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

This document records the variables contained in the data used
for the Building Energy EDA. The data consists of two parts:
metadata and individual building data.

# Metadata

The metadata is characteristics about each building in general.
Each row is a single building and the columns contain the following variables.

|      Variable     |    Type   | Units | Explanation                                        |
|:-----------------:|:---------:|:-----:|----------------------------------------------------|
| Ref               | integer   |       | Reference number for building                      |
| Name              | character |       | Assigned Name of building                          |
| City              | character | kWh   | City location of building                          |
| State             | character |       | State location of building                         |
| Square Footage    | integer   | sq ft | Square footage of building                         |
| Years of data     | integer   | years | Number of years of complete data for building      |
| Climate Zone      | character |       | Koppen-Geiger climate zone                         |
| Customer          | character |       | Company owning building (Progressive)              |
| Annual Consumption | integer   | kWh   | Average annual electricity consumption of building |
| Country           | character |       | Country location of building (United States)       |


The final cleaned version of the building metadata is saved in the 
metadata directory.

# Building Data

The building data contains all the energy use, weather conditions, and time
information for each building over the entire period of study. Each row is one
15-minute interval and the columns contain the variables. There were eight buildings
in the study, and each building was in its own comma separated value files. The file
names ('f-weather_building.csv') represent that the data contains forecasted 
electricity consumption and complete weather information. 

|     Variable     |    Type   | Units | Meaning                                   |
|:----------------:|:---------:|:-----:|-------------------------------------------|
| timestamp        | date      |       | date and time                             |
| elec_cons        | numeric   | kWh   | electricity consumption                   |
| elec_cons_imp    | integer   |       | electricity consumption imputed           |
| power_dem        | numeric   | kW    | power difference                          |
| biz_day          | integer   |       | business day                              |
| day_of_week      | character |       | day of the week                           |
| week_day_end     | character |       | weekday or weekend                        |
| sun_rise_set     | character |       | sun rise or sun set                       |
| num_time         | numeric   | hours | time in hours from start of day           |
| cleaned_energy   | number    | kWh   | energy consumption with anomalies removed |
| anom_flag        | integer   |       | anomaly flag                              |
| ghi              | integer   | W/m^2 | global horizontal irradiance              |
| dif              | integer   | W/m^2 | diffuse horizontal irradiance             |
| gti              | integer   | W/m^2 | global tilted irradiance                  |
| temp             | numeric   | C     | temperature                               |
| rh               | numeric   | %     | relative humidity                         |
| pwat             | numeric   | cm    | precipitable water                        |
| ws               | numeric   | kph   | wind speed                                |
| forecast         | numeric   | kWh   | cleaned energy forecast                   |
| anom_missed_flag | integer   |       | anomaly or missing data flag              |


Not all of the variables were examined in the initial modeling of the data by the EDIFES team.
The following variables were of primary interest to the EDIFES team on the first pass through the data.

* timestamp: gives the date and time for the energy measurement in fifteen minute intervals
* elec_cons: the raw electricity consumption data (kWh)
* elec_cons_imp: 1 or 0 marker if the data was linearly imputed
* power_dem: difference in power (kW) between measurements
* biz_day: business day or not (accounts for holidays)
* day_of_week: relatively self-explanatory
* week_day_end: weekday or weekend
* num_time: number of hours since the start of day
* ghi: global horizontal irradiance
generally positively correlated with energy consumption during the summer
* temp: most correlated weather variable with energy consumption
* rh: relative humidity
* forecast: final cleaned energy consumption with anomalies removed and missing 
data imputed using a custom function
* anom_missed_flag: marker that tells if forecast energy had to be corrected from the raw number. 
There would be two reasons for the raw data to be corrected:the data was
missing, or the data was anomalous (an outlier). 

The final cleaned versions of the individual building datasets are 
saved in the data directory. 

# Feather Data

The feather file format was used to transfer dataframes between R and Python for
the machine learning portion of the project. All of the feather files 
can be found in the feather directory. 