---
title: "Semester Project Update"
author: "Will Koehrsen"
date: "November 26, 2017"
output: 
  pdf_document:
  toc: true
  number_sections: true
url_color: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Define Question

Which explanatory variables are most highly correlated with building energy consumption,
and is it possible to build a model to accurately map the relationship between these features and 
the response? 

# Cleaning and EDA

Cleaning was not required for my semester project because I received 8 cleaned building
datasets from the EDIFES team. However, over the course of my project,
I did have to correct the anomalously low energy consumption of the CoServ building. 
I later found out the other team members had done this as well when examining 
the Progressive dataset. My data structure is a single dataframe for each building
where every row is a 15-minute interval and the columns are the variables. The variables 
include both raw and cleaned energy consumption (in kWh), temperature, ghi, 
relative humidity, time of day in hours, a timestamp, business or non-business day, and sun rise or sun set among others. 
Each building dataset was contained in a separate comma-separated value (CSV) file
that could easily be read into R as a dataframe. I was fortunate in that I did not
have to spend a significant amount of time in my analysis aquiring and cleaning data.
I did seek out a secondary source of data from the City of Chicago in order to 
determine the relationship between square footage of a building and annual energy consumption. 
A limitation of the data I had was that there were only eight buildings, making
comparisons betweeen buildings statistically meaningless. Each building had tens
of thousands of datapoints, but there were simply not enough buildings to 
allow me to compare energy consumption across climate zones and between 
office buildings of varying sizes. 
The explaratory data analysis primarily demonstrated the many different patterns
within building energy consumption data. There are daily, weekly, seasonal, and yearly trends in each 
data series that vary significantly across climate zones. Any model that attempts
to predict and/or forecast energy consumption must therefore be flexible 
enough to capture all of the individual trends. Moreover, EDA revealed the most highly
correlated weather variable with energy consumption was temperature followed by global 
horizontal irradiance. 
In terms of all the variables, modeling showed that the time of day in hours
as well as whether or not the day was a business day was also strongly
correlated with energy consumption. None of these findings
should be especially surprising, but it was nice to have confirmation of our 
intuitive hypotheses. The EDA also showed (using the Chicago building dataset) that
the relationship between building size and annual energy consumption is linear on 
a log-log scale. Finally, the EDA explored three different models covering the complexity
spectrum to assess each one for predictive capabilities. 
The linear regression proved to be completely incapable of predicing
energy from the explanatory variables for 15-minute intervals.
A support vector machine regressor performed slightly better, but also did not 
have impressive results even though it had been the most commonly used approach in the literature. 
In contrast, the Random Forest Regressor demonstrated exceedingly high accuracy on a random 
training/testing split of the data. When tasked with predicing the energy consumption
from all of the weather and time variables, the Random Forest achieved a 6% MAPE 
and a R-Squared of greater than 0.95 on the test set
averaged across all of the buildings. Therefore, the Random Forest was selected for further
examination for forecasting capabilities in the modeling section of Report Three.

# Modeling and Statistical Learning

I choose to approach this problem as supervised regression. It is supervised because 
we know both the features (the weather and time explanatory variables), and the 
correct labels (the energy consumption response). During training, we therefore can 
give the models both the independent and dependent variables so they 
can learn the mapping between the two. On the test set, we withhold the labels from the model and
ask it to make predictions with only the labels. This allows us to learn 
evaluate the accuracy of the predictions against the known true values. 
The predictors are the weather and time variables (including aspects such as business day
or day of the week) and the response is the energy consumption. 

I approached the problem with two different timescales: first, I used linear regression
to try and predict average daily energy consumption, then, I used the three models outline above
for predictions of energy consumption every 15-minutes. 
The Random Forest significantly outperformed the other methods (Linear Regression and SVM Regression) when
asked to predict energy in 15-minute intervals. Furthermore, it is able to return
feature importances which showed that temperature is the most highly correlated
variable with energy consumption, in agreement with correlation coefficients. 
Not surprisingly, the other highly correlated variables were the time of day, business day, 
diffuse irradiance, and ghi. I also used the Random Forest to simulate a 2 degree Celsius
increase in temperatures over the course of a year. This experiment was 
designed to mimic the effects of global warming and the 
investigation proved to be successful. I have documented the results in report 3.
 
Once I had confirmed that the Rnadom Forest could predict energy consumption when the 
weather and time variables were known, I wanted to see if it could forecast into the future
where no accurate weather data is available. However, the Random Forest requires the same number 
of features during prediction as during training so I needed some source of weather.
I decided to use the weather from exactly one year prior to the date as the best 
estimate. I then removed the final four months of the data to use as a testing set 
and I pretended we had no knowledge of the weather during that period. I matched
the weather data from the previous year to the final four months and made
predictions with the trained Random Forest. Unfortunately, the model was not able to forecast 
with an acceptable level of accuracy and I concluded that weather was too variable
to be used across years. Therefore, a different approach will be required 
for forecasting. One promising contendor is a General Additive Model, which breaks down
a time series into a number of time patterns and an overall trend. 

# Final Models and Conclusions

The results of the modeling have been exhaustively documented in report 3. 
The Random Forest proved to be the best model for prediction but cannot accurately forecast 
energy consumption into the future. Additional methods such as general additive models 
(using the prophet package in Python or R) will need to be tried for the 
forecasting problem. 

The major conclusions from the entire project are the correlations
between predictors and energy consumption. In order for buildings to use less energy,
they must be better equipped to deal with severe temperature
gradients and with intense sunlight. Recommendations along these 
lines would be for building owners to invest in proper insulation and seals,
consider covering windows in direct sunlight, and 
construct buildings to take advantage of passive heating from the sun in the winter
without absorbing excess heating in the summer. 
These recommendations would need to be tailored to the specific climate zone because
energy consumption patterns diverge significantly across the expanse of the United States. 
Furthermore, the Random Forest model can be used to carry out experiments on existing
data, such as observing the effect of changing the precipitation or wind speed. 
Maybe this could be extended to changing aspects of the biding
such as would occur with a retrofit and 
observing the results. The Random Forest allows us to replay the past, but 
it cannot predict the future with and accuracy
because of the lack of future weather data. 
Therefore, an area I would like to look at as a result of this EDA is general additive models. 
I have experimented with them a little and have seen 
how they are able to separate out weekly, seasonal, and overall trends 
and then make future predictions. The Progressive Building Energy EDA did not make any astounding 
discoveries, but it gave me great experience in the domain
of building energy and it allowed me to 
try out some of the methods used by the EDIFES team 
as well as others that will now be incorporated into the project. At the end of the 
EDA, I find I have more questions than I started with which I believe is a 
positive indicator. Moving forward, I will be able to build on the work 
in this EDA and explore additional data science techniques 
that I did not have the chance to employ. 
